---

- name: Insert Filebeat prespector to configuration.
  lineinfile:
    dest: "{{ filebeat_config_file }}"
    line: '- {{ item | to_json }}'
    insertafter: "^filebeat.prospectors:$"
  with_items: "{{ filebeat_prospectors }}"
  notify: restart filebeat
  become: yes

